//test
var TIER_NAMES = [ null, "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eight" ];
var DISPLAY_NAMES = [ null, "First", "Second", "Third", "Fourth", "Fifth", "Sixth", "Seventh", "Eighth" ];
var player = {
  money: O(10),
  tickSpeedCost: O(1000),
  tickspeed: O(1000),
  firstCost: O(10),
  secondCost: O(100),
  thirdCost: O(10000),
  fourthCost: O(1000000),
  fifthCost: O(1e9),
  sixthCost: O(1e13),
  seventhCost: O(1e18),
  eightCost: O(1e24),
  firstAmount: O(0),
  secondAmount: O(0),
  thirdAmount: O(0),
  fourthAmount: O(0),
  firstBought: 0,
  secondBought: 0,
  thirdBought: 0,
  fourthBought: 0,
  fifthAmount: O(0),
  sixthAmount: O(0),
  seventhAmount: O(0),
  eightAmount: O(0),
  fifthBought: 0,
  sixthBought: 0,
  seventhBought: 0,
  eightBought: 0,
  firstPow: O(1),
  secondPow: O(1),
  thirdPow: O(1),
  fourthPow: O(1),
  fifthPow: O(1),
  sixthPow: O(1),
  seventhPow: O(1),
  eightPow: O(1)
  }
